[common]
version = 2
import_std = [
	"fs",
	"process",
]
build_flags = ["--tests"]

[sandbox]
kind = "Bubblewrap"

[pkg.allocator-api2]
allow_unsafe = true

[pkg.async-stream]
allow_proc_macro = true

[pkg.async-trait]
allow_proc_macro = true
build.allow_apis = [
    "process",
]
allow_unsafe = true

[pkg.autocfg]
from.build.allow_apis = [
    "fs",
    "process",
]

[pkg.bytes]
allow_unsafe = true

[pkg.darling_macro]
allow_proc_macro = true

[pkg.derivative]
allow_proc_macro = true

[pkg.dyn-clone]
allow_unsafe = true

[pkg.futures-channel]
allow_unsafe = true

[pkg.futures-core]
allow_unsafe = true

[pkg.futures-macro]
allow_proc_macro = true
allow_unsafe = true

[pkg.futures-sink]
allow_unsafe = true

[pkg.futures-task]
allow_unsafe = true

[pkg.httparse]
allow_unsafe = true

[pkg.iana-time-zone]
allow_unsafe = true

[pkg.itoa]
allow_unsafe = true

[pkg.kube-derive]
allow_proc_macro = true

[pkg.libc]
build.allow_apis = [
	"process",
]
allow_unsafe = true

[pkg.log]
allow_unsafe = true

[pkg.once_cell]
allow_unsafe = true

[pkg.percent-encoding]
allow_unsafe = true

[pkg.pest_derive]
allow_proc_macro = true

[pkg.pin-project-internal]
allow_proc_macro = true
allow_unsafe = true

[pkg.pin-project-lite]
allow_unsafe = true

[pkg.pin-utils]
allow_unsafe = true

[pkg.ppv-lite86]
allow_unsafe = true

[pkg.proc-macro2]
build.allow_apis = [
	"fs",
	"process",
]
allow_unsafe = true

[pkg.ryu]
allow_unsafe = true

[pkg.schemars_derive]
allow_proc_macro = true

[pkg.scopeguard]
allow_unsafe = true

[pkg.serde]
build.allow_apis = [
	"process",
]
allow_unsafe = true

[pkg.serde_derive]
allow_proc_macro = true

[pkg.spin]
allow_unsafe = true

[pkg.syn]
build.allow_apis = [
	"process",
]
allow_unsafe = true

[pkg.thiserror]
build.allow_apis = [
	"fs",
	"process",
]

[pkg.thiserror-impl]
allow_proc_macro = true

[pkg.tokio-macros]
allow_proc_macro = true

[pkg.tracing-attributes]
allow_proc_macro = true

[pkg.try-lock]
allow_unsafe = true

[pkg.unicode-ident]
allow_unsafe = true

[pkg.version_check]
from.build.allow_apis = [
    "process",
]

[pkg.wasm-bindgen-macro]
allow_proc_macro = true

[pkg.zerocopy]
allow_unsafe = true

[pkg.zerocopy-derive]
allow_proc_macro = true

[pkg.k8s-openapi]
build.allow_apis = [
    "fs",
]
build.allow_build_instructions = [
    "cargo:version=71936",
]

[pkg.form_urlencoded]
allow_unsafe = true

[pkg.memchr]
allow_unsafe = true

[pkg.tracing-core]
allow_unsafe = true

[pkg.bitflags]
allow_unsafe = true

[pkg.smallvec]
allow_unsafe = true

[pkg.zeroize]
allow_unsafe = true

[pkg.http]
allow_unsafe = true

[pkg.unsafe-libyaml]
allow_unsafe = true

[pkg.either]
allow_unsafe = true

[pkg.aho-corasick]
allow_unsafe = true

[pkg.getrandom]
allow_unsafe = true

[pkg.signal-hook-registry]
allow_unsafe = true

[pkg.num_cpus]
allow_unsafe = true

[pkg.socket2]
allow_unsafe = true

[pkg.mio]
allow_unsafe = true

[pkg.cc]
allow_unsafe = true
from.build.allow_apis = [
    "fs",
    "process",
]

[pkg.parking_lot_core]
allow_unsafe = true

[pkg.http-body]
allow_unsafe = true

[pkg.serde_json]
allow_unsafe = true

[pkg.rand_core]
allow_unsafe = true

[pkg.ahash]
allow_unsafe = true

[pkg.regex-automata]
allow_unsafe = true

[pkg.ring]
build.allow_apis = [
    "fs",
    "process",
]
build.allow_build_instructions = [
	"cargo:rustc-env=RING_CORE_PREFIX=*",
	"cargo:rustc-link-lib=static=ring",
	"cargo:rustc-link-lib=static=ring-core",
	"cargo:rustc-link-lib=static=ring-test",
	"cargo:rustc-link-lib=static=ring_core_0_17_8_",
	"cargo:rustc-link-lib=static=ring_core_0_17_8_test",
	"cargo:rustc-link-search=native=*",
]
allow_unsafe = true

[pkg.rand_chacha]
allow_unsafe = true

[pkg.hashbrown]
allow_unsafe = true

[pkg.tracing]
allow_unsafe = true

[pkg.rand]
allow_unsafe = true

[pkg.pest]
allow_unsafe = true

[pkg.indexmap]
allow_unsafe = true

[pkg.tokio]
allow_unsafe = true

[pkg.pin-project]
allow_unsafe = true

[pkg.pest_generator]
allow_apis = [
    "fs",
]

[pkg.serde_yaml]
allow_unsafe = true

[pkg.slab]
allow_unsafe = true

[pkg.lock_api]
allow_unsafe = true

[pkg.num-traits]
allow_unsafe = true

[pkg.tokio-util]
allow_unsafe = true

[pkg.parking_lot]
allow_unsafe = true

[pkg.futures-util]
allow_unsafe = true

[pkg.ordered-float]
allow_unsafe = true

[pkg.chrono]
allow_unsafe = true

[pkg.hyper]
allow_unsafe = true
