# See all available configuration options at:
# https://embarkstudios.github.io/cargo-deny/index.html

# --------------------------------------------------
# BANS
# --------------------------------------------------

[bans]
# The graph highlighting used when creating dotgraphs for crates.
highlight = "all"
# The lint level for when a crate version requirement is set to `*`.
wildcards = "deny"
# Lint level for when multiple versions of the same crate are detected.
multiple-versions = "allow"
# The default lint level for `default` features for workspace crates.
workspace-default-features = "allow"
# The default lint level for `default` features for external crates.
external-default-features = "allow"

# --------------------------------------------------
# SOURCES
# --------------------------------------------------

[sources]
# What to do when encountering a repository from a host not in the allow list.
unknown-git = "deny"
# What to do when encountering a crate from a registry not in the allow list.
unknown-registry = "deny"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

# --------------------------------------------------
# ADVISORIES
# --------------------------------------------------

[advisories]
# The url(s) of the advisory databases to use.
db-urls = ["https://github.com/rustsec/advisory-db"]
# The path where the advisory database is cloned/fetched into.
db-path = "~/.cargo/advisory-db"
# The lint level for crates that have been yanked.
yanked = "warn"

# --------------------------------------------------
# LICENSES
# --------------------------------------------------

[licenses]
# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.95

# List of explicitly allowed licenses from https://spdx.org/licenses
allow = [
	"MIT",
	"ISC",
	"Zlib",
	"BSL-1.0",
	"Apache-2.0",
	"BSD-3-Clause",
	"OpenSSL",
	"Unlicense",
]

# List of exception allowed licenses from https://spdx.org/licenses
exceptions = [
	{ allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
	{ path = "LICENSE", hash = 0xbd0eed23 }
]
