[graph]
targets = [
    "x86_64-unknown-linux-musl",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0384", reason = "This crate is no longer maintained, and it will be removed" },
]

[licenses]
allow = [
    "Unicode-3.0",
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "OpenSSL",
    "BSL-1.0",
    "Zlib",
]
confidence-threshold = 0.8

[[licenses.clarify]]
crate = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = false
registries = [
    #"https://sekretz.com/registry
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
