extend = [
	{ path = "Makefile.development.toml" },
	{ path = "Makefile.docker.toml" },
	{ path = "Makefile.release.toml" },
]

env_files = [
	{ path = "./.env" },
	{ path = "./development.env", profile = "development" },
	{ path = "./release.env", profile = "release" }
]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.empty]
disabled = true
private = true

[tasks.init]
private = true

[tasks.end]
private = true

[tasks.clean]
category = "LOCAL"
command = "cargo"
args = ["clean"]
