apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dappproducts.dappmesh.io
spec:
  group: dappmesh.io
  names:
    kind: DappProduct
    listKind: DappProductList
    singular: dappproduct
    plural: dappproducts
    shortNames:
      - product
      - products
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
              required: [ "name" ]
