version: v2beta1
name: dappmesh-product-operator

dependencies:
  core:
    path: ../../
    pipeline: dev

vars:
  DEVSPACE_ENV_FILE: ".env"

pipelines:
  dev:
    run: |-
      run_dependency_pipelines core
      start_dev app

dev:
  app:
    namespace: dappmesh
    labelSelector:
      app: dapp-product-operator
    devImage: ghcr.io/dappmesh/${DEVSPACE_CONTAINER_NAME}:${DEVSPACE_CONTAINER_TAG}
    sync:
      - path: ../../../../target/${DEVSPACE_TARGET_PLATFORM}/debug/dapp-product-operator:/app/dapp-product-operator
        file: true
        startContainer: true
        onUpload:
          restartContainer: true
    command: [ "./dapp-product-operator" ]
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
