version: v2beta1
name: dappmesh-app

dependencies:
  product-operator:
    path: ../core/operator/product
    pipeline: dev

pipelines:
  dev:
    run: |-
      run_dependency_pipelines --all
      create_deployments data-product

deployments:
  data-product:
    namespace: dappmesh
    kubectl:
      manifests:
        - ./product/**