name: ✨ New Feature
description: Creating a new feature
title: "[FEATURE] <title>"
labels: ["Feature", "Needs Triage"]
body:
  - type: textarea
    attributes:
      label: Overview
      description: Provide an overview of the feature request.
      placeholder: Provide information here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: List all requirements for ticket completion.
      placeholder: "- [ ] List requirements here"
      value: "- [ ] Requirement 1"
  - type: textarea
    attributes:
      label: Related issues
      description: Link to any related or prior issues.
      placeholder: List related issues here if available.
      value: "- #"
  - type: textarea
    attributes:
      label: Design and documentation reference
      description: Provide links to design and/or documentation if available.
      placeholder: "[Reference](url)"
      value: "[Reference name](url)"
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything that will give us more context about the new feature you are creating!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
