version: v2beta1
name: dappmesh-mesh-operator

dependencies:
  platform:
    path: ../../
    pipeline: dev

vars:
  DEVSPACE_ENV_FILE: ".env"

pipelines:
  dev:
    run: |-
      run_dependency_pipelines platform
      start_dev app

dev:
  app:
    namespace: dappmesh
    labelSelector:
      app: dapp-mesh-operator
    devImage: ghcr.io/dappmesh/devspace-container:${DEVSPACE_CONTAINER_TAG}
    sync:
      - path: ../../../../target/${DEVSPACE_TARGET_PLATFORM}/debug/dapp-mesh-operator:/app/dapp-mesh-operator
        file: true
        startContainer: true
        onUpload:
          restartContainer: true
    command: [ "./dapp-mesh-operator" ]
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
