
# cargo-vet config file

[cargo-vet]
version = "0.9"

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.77"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.backoff]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.2"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.34"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.derivative]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dyn-clone]]
version = "1.0.16"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.http-range-header]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.28"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.60"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.68"
criteria = "safe-to-deploy"

[[exemptions.json-patch]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.jsonpath-rust]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.k8s-openapi]]
version = "0.21.1"
criteria = "safe-to-deploy"

[[exemptions.kube]]
version = "0.88.1"
criteria = "safe-to-deploy"

[[exemptions.kube-client]]
version = "0.88.1"
criteria = "safe-to-deploy"

[[exemptions.kube-core]]
version = "0.88.1"
criteria = "safe-to-deploy"

[[exemptions.kube-derive]]
version = "0.88.1"
criteria = "safe-to-deploy"

[[exemptions.kube-runtime]]
version = "0.88.1"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.153"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.1"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.pem]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.7.7"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.7.7"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.7.7"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.7.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.78"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.35"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.3"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.10"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.101.7"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.serde-value]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde_derive_internals]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.57"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.57"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.36.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-io-timeout]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.treediff]]
version = "4.0.3"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unsafe-libyaml]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.91"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.91"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.91"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.91"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.91"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"
