
# cargo-vet config file

[cargo-vet]
version = "0.9"

[[exemptions.addr2line]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.86"
criteria = "safe-to-run"

[[exemptions.assert-json-diff]]
version = "2.0.2"
criteria = "safe-to-run"

[[exemptions.async-broadcast]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.async-stream]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.async-stream-impl]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.80"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.backoff]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.73"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.16.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.38"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.20"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.derivative]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dyn-clone]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.fluent-uri]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.headers]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.headers-core]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.9.4"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.hyper-http-proxy]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.2"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.60"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.2.6"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.13"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.json-patch]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.jsonpath-rust]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.jsonptr]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.k8s-openapi]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.kube]]
version = "0.92.1"
criteria = "safe-to-deploy"

[[exemptions.kube-client]]
version = "0.92.1"
criteria = "safe-to-deploy"

[[exemptions.kube-core]]
version = "0.92.1"
criteria = "safe-to-deploy"

[[exemptions.kube-derive]]
version = "0.92.1"
criteria = "safe-to-deploy"

[[exemptions.kube-runtime]]
version = "0.92.1"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.155"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.1"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.pem]]
version = "3.0.4"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.7.10"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.7.10"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.7.10"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.7.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.86"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.36"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.5"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.10"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.4"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.203"
criteria = "safe-to-deploy"

[[exemptions.serde-value]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.203"
criteria = "safe-to-deploy"

[[exemptions.serde_derive_internals]]
version = "0.29.1"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.117"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml]]
version = "0.9.34+deprecated"
criteria = "safe-to-deploy"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.67"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.61"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.61"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.8"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.38.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.15"
criteria = "safe-to-run"

[[exemptions.tokio-test]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.tokio-util]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-test]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-serde]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.18"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unsafe-libyaml]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"
