version: v2beta1
name: dappmesh-platform

dependencies:
  infra:
    path: ../infra
    pipeline: dev

pipelines:
  dev:
    run: |-
      run_dependency_pipelines infra
      create_deployments platform-crds
      create_deployments platform-operators

deployments:
  platform-crds:
    namespace: dappmesh
    kubectl:
      manifests:
        - ./crds/**

  platform-operators:
    namespace: dappmesh
    kubectl:
      manifests:
        - ./operator/**
