apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ part.of }}
    app.kubernetes.io/version: {{ version }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ port }}
      targetPort: http
      protocol: TCP