apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ part.of }}
    app.kubernetes.io/version: {{ version }}