apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ part.of }}
    app.kubernetes.io/version: {{ version }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ storage.quantity }}