version: v2beta1
name: dappmesh-domain-operator

dependencies:
  platform:
    path: ../../
    pipeline: dev

vars:
  DEVSPACE_CONTAINER_TAG:
    source: env

pipelines:
  dev:
    run: |-
      run_dependency_pipelines platform
      start_dev app

dev:
  app:
    namespace: dappmesh
    labelSelector:
      app: dapp-domain-operator
    devImage: ghcr.io/dappmesh/devspace-container:${DEVSPACE_CONTAINER_TAG}
    sync:
      - path: ../../../../target/x86_64-unknown-linux-musl/debug/dapp-domain-operator:/app/dapp-domain-operator
        file: true
        startContainer: true
        onUpload:
          restartContainer: true
    command: [ "./dapp-domain-operator" ]
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl