apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dappdomains.dappmesh.io
spec:
  group: dappmesh.io
  names:
    kind: DappDomain
    listKind: DappDomainList
    singular: dappdomain
    plural: dappdomains
    shortNames:
      - domain
      - domains
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
              required: [ "name" ]
