apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-auth
  namespace: traefik
type: kubernetes.io/basic-auth
stringData:
  username: "dappmesh"
  password: "dappmesh"